#!/bin/sh
#
# Purge tsdb cache.

. /etc/sysconfig/tsdb-server

test -n "$CACHE" || exit
test -n "$CACHE_SIZE" || exit
cd $CACHE || exit

# Convert to bytes.
maxbytes=$(echo "$CACHE_SIZE * 1048576" | bc)

# Least recently used policy.
find $CACHE -mindepth 1 -maxdepth 1 -type f -printf '%A@ %s %p\n' | \
sort -rn | \
awk -v maxbytes=$maxbytes '
	{ sum += $2 }
	sum > maxbytes { print $3 }
' | \
xargs rm -f
